### ISSUE TITLE
Mise en conformité du protocole d'échange Warehouse -> App - route GET /tour

### ISSUE THREAD

**Issue by ttben** [ttben/al-drone-delivery#2]
de mémoire nous nous étions mis d'accord, via le mail "[AL - Projet] Genius TCI, Boulot et cacahuète" du 31/10 sur le protocole suivant :

GET /tour :

`[
  {
    "location": "location info",
    "deliveries": [
      {
        "drone": "droneID",
        "package": "packageID",
        "droneAlt": [
          "droneID"
        ]
      }
    ]
  }
]`

sauf erreur de notre part (ce qui est fort probable) le code actuel retourne

`{
  "dropPoints": [
    {
      "location": {
        "name": "here"
      },
      "deliveries": [
        {
          "drone": "drone1",
          "box": "package1",
          "droneAlt": [
            "drone3"
          ]
        }
      ]
    }
  ]
}`

Merci de fix ou de nous engueuler parce qu'on s'est trompé !

**Comment by NabilEL** [comment]
C'est fix, a part pour le "package" qui reste en "box", parce que c'est déjà un mot clé du langage.

**Comment by etiennestrobbe** [comment]
oui c'est bien "box" qu'il faut :)

2015-11-09 21:55 GMT+01:00 NabilEL <notifications@github.com>:
