### ISSUE TITLE
Ouvrir une route pour récupérer la description d'une Box

### ISSUE THREAD

**Issue by ttben** [ttben/al-drone-delivery#3]

**Comment by ttben** [comment]
Ou pour récupérer toutes les Box d'une mission .. ?

**Comment by NabilEL** [comment]
Genre à partir de l'id, tu recup dimensions et poids ?

**Comment by ttben** [comment]
et destination surtout

2015-11-09 22:05 GMT+01:00 NabilEL <notifications@github.com>:

> Genre à partir de l'id, tu recup dimensions et poids ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ttben/al-drone-delivery/issues/3#issuecomment-155192974>
> .
>



-- 
Benjamin Benni
Étudiant ingénieur en Sciences Informatique
5ième année - Architecture logicielle
Polytech Nice - Sophia Antipolis

**Comment by NabilEL** [comment]
Y a une interface, faudra définir la tronche des id des drone.
