### ISSUE TITLE
[APP] - fork

### ISSUE THREAD

**Issue by ttben** [ttben/al-drone-delivery#4]
Une branche dédiée au développement de l'application android est crée,
une branche dédiée au développement / test du modèle actuel

**Comment by ttben** [comment]
Tu vois ce commentaire etienne ?

**Comment by etiennestrobbe** [comment]
oui

**Comment by ttben** [comment]
On fork depuis quelle branche ? dev-app ?
dev-app-model
dev-app-android

et dev-app devient une branche d'intégration pour nous deux 
cela te convient ?

**Comment by etiennestrobbe** [comment]
je réponds par étape : dev-app comme branche d'inté -> OK

**Comment by etiennestrobbe** [comment]
si dev-app est la dernière version fonctionnel, on part de dev-app.
dev-app-android pour le dev de l'appli android OK
dev-app-model pour la partie du jar OK

**Comment by ttben** [comment]
Ok je branche ça

**Comment by toms-dev** [comment]
hangout ou quoi les gars?

2015-11-13 10:33 GMT+01:00 Strobbe Etienne <notifications@github.com>:

> je réponds par étape : dev-app comme branche d'inté -> OK
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ttben/al-drone-delivery/issues/4#issuecomment-156376957>
> .
>



-- 
*Étudiant en Sciences Informatiques à *Polytech Nice - Sophia Antipolis

**Comment by ttben** [comment]
C'est fait !

**Comment by ttben** [comment]
putain mais ... on pas build ton appli en fait ? comment on fait pour le déploiement continu ?

**Comment by etiennestrobbe** [comment]
Il faut qu'un test un build Gradle sur Travis (sur un truc à part) pour tenter de l'ajouter dans notre projet

**Comment by toms-dev** [comment]
hangout bordel

Le 13 novembre 2015 10:40, Strobbe Etienne <notifications@github.com> a
écrit :

> Il faut qu'un test un build Gradle sur Travis (sur un truc à part) pour
> tenter de l'ajouter dans notre projet
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ttben/al-drone-delivery/issues/4#issuecomment-156378562>
> .
>



-- 
*Étudiant en Sciences Informatiques à *Polytech Nice - Sophia Antipolis

**Comment by ttben** [comment]
j'aime tes discussions, où on est informé qu'on spam, par une agression
#teamSpirit.
Alors va chier, et on fait ce qu'on veut.
VOILA.



non sans dec ok on arrête. <3


2015-11-13 10:41 GMT+01:00 Tom Guillermin <notifications@github.com>:

> hangout bordel
>
> Le 13 novembre 2015 10:40, Strobbe Etienne <notifications@github.com> a
> écrit :
>
> > Il faut qu'un test un build Gradle sur Travis (sur un truc à part) pour
> > tenter de l'ajouter dans notre projet
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ttben/al-drone-delivery/issues/4#issuecomment-156378562
> >
> > .
> >
>
>
>
> --
> *Étudiant en Sciences Informatiques à *Polytech Nice - Sophia Antipolis
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ttben/al-drone-delivery/issues/4#issuecomment-156378720>
> .
>



-- 
Benjamin Benni
Étudiant ingénieur en Sciences Informatique
5ième année - Architecture logicielle
Polytech Nice - Sophia Antipolis

**Comment by toms-dev** [comment]
​

Le 13 novembre 2015 10:42, Benjamin Benni <notifications@github.com> a
écrit :

> j'aime tes discussions, où on est informé qu'on spam, par une agression
> #teamSpirit.
> Alors va chier, et on fait ce qu'on veut.
> VOILA.
>
>
>
> non sans dec ok on arrête. <3
>
>
> 2015-11-13 10:41 GMT+01:00 Tom Guillermin <notifications@github.com>:
>
> > hangout bordel
> >
> > Le 13 novembre 2015 10:40, Strobbe Etienne <notifications@github.com> a
> > écrit :
> >
> > > Il faut qu'un test un build Gradle sur Travis (sur un truc à part) pour
> > > tenter de l'ajouter dans notre projet
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/ttben/al-drone-delivery/issues/4#issuecomment-156378562
> > >
> > > .
> > >
> >
> >
> >
> > --
> > *Étudiant en Sciences Informatiques à *Polytech Nice - Sophia Antipolis
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ttben/al-drone-delivery/issues/4#issuecomment-156378720
> >
> > .
> >
>
>
>
> --
> Benjamin Benni
> Étudiant ingénieur en Sciences Informatique
> 5ième année - Architecture logicielle
> Polytech Nice - Sophia Antipolis
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ttben/al-drone-delivery/issues/4#issuecomment-156378859>
> .
>



-- 
*Étudiant en Sciences Informatiques à *Polytech Nice - Sophia Antipolis
